In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,11).reshape(5,2) #reshape(rows,columns)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# np.ones & np.zeroes

np.ones((3,4))  #it is used to intialize

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# np.random
np.random.random((3,4))  #it is used to intialize


array([[0.29604401, 0.05953409, 0.3955286 , 0.76877071],
       [0.64260492, 0.36596386, 0.72591164, 0.94473285],
       [0.94063021, 0.97343028, 0.90499844, 0.68288942]])

In [10]:
# np.linspace
np.linspace(-10,10,10) # generates linearnly seperable points

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [12]:
# ndim: no od dimensions
a1 = np.arange(10)
a1.ndim

1

In [13]:
a2 = np.arange(12).reshape(3,4)
a2.ndim

2

In [14]:
a3 = np.arange(12).reshape(2,3,2)
a3.ndim

3

In [15]:
# shape 
a1.shape

(10,)

In [16]:
a2.shape

(3, 4)

In [17]:
a3.shape

(2, 3, 2)

In [18]:
# size
a3.size

12

In [19]:
# itemsize
a3.itemsize

4

In [20]:
a3.dtype

dtype('int32')

# Changing Datatype

In [21]:
# astype
a3.astype(np.int64)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]], dtype=int64)

In [22]:
a3.astype(np.int32)
a3.dtype

dtype('int32')

# Array Operations

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)


In [24]:
# scaler operations

#arithmetic

a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [25]:
# relational operators

a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
# vector operations
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Funtions

In [28]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 3., 34., 71.],
       [62., 97., 96.],
       [ 8., 78., 77.]])

In [29]:
# max/min/sum/prod
# axis = 0(col) & axis = 1(column)
np.max(a1, axis =1)
np.max(a1, axis =0)

array([62., 97., 96.])

In [30]:
# mean/median/std/var
np.mean(a1, axis = 1)

array([36.        , 85.        , 54.33333333])

In [31]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [32]:
np.log(a1)

array([[1.09861229, 3.52636052, 4.26267988],
       [4.12713439, 4.57471098, 4.56434819],
       [2.07944154, 4.35670883, 4.34380542]])

In [33]:
np.exp(a1)

array([[2.00855369e+01, 5.83461743e+14, 6.83767123e+30],
       [8.43835667e+26, 1.33833472e+42, 4.92345829e+41],
       [2.98095799e+03, 7.49841700e+33, 2.75851345e+33]])

In [34]:
# round/floor/ceil

# Indexing & Slicing

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a2[1,0]    # a[row,col]

4

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
a3[1,0,1] 

5

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[2:5] # same as python list

array([2, 3, 4])

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2[0,:]

array([0, 1, 2, 3])

In [44]:
a2[:,2]

array([ 2,  6, 10])

In [45]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [46]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [47]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [48]:
a2[1:2,::3]

array([[4, 7]])

In [49]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [50]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[0,1::2,]

array([[3, 4, 5]])

# Iterating

In [53]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [54]:
a2 
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [55]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [56]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [57]:
# Tranpose == T
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [59]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [61]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [62]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [65]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [66]:
# horizontal
# np.hsplit(array_name, no_of_parts)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [68]:
# vertical
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]