In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([42, 74, 63, 42, 99, 77, 95, 44,  1, 98, 23, 11, 38, 90, 45])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[78, 86, 88, 97],
       [29, 72,  8, 71],
       [80, 14, 38, 65],
       [74, 97, 10, 41],
       [17, 44, 91, 40],
       [81, 15, 20, 71]])

In [4]:
np.sort(a)

array([ 1, 11, 23, 38, 42, 42, 44, 45, 63, 74, 77, 90, 95, 98, 99])

In [5]:
np.sort(b)

array([[78, 86, 88, 97],
       [ 8, 29, 71, 72],
       [14, 38, 65, 80],
       [10, 41, 74, 97],
       [17, 40, 44, 91],
       [15, 20, 71, 81]])

In [6]:
np.sort(b, axis = 0)

array([[17, 14,  8, 40],
       [29, 15, 10, 41],
       [74, 44, 20, 65],
       [78, 72, 38, 71],
       [80, 86, 88, 71],
       [81, 97, 91, 97]])

In [7]:
np.append(a,200)

array([ 42,  74,  63,  42,  99,  77,  95,  44,   1,  98,  23,  11,  38,
        90,  45, 200])

In [8]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[78., 86., 88., 97.,  1.],
       [29., 72.,  8., 71.,  1.],
       [80., 14., 38., 65.,  1.],
       [74., 97., 10., 41.,  1.],
       [17., 44., 91., 40.,  1.],
       [81., 15., 20., 71.,  1.]])

In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [13]:
np.concatenate((c,d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
e = np.array([1,1,2,2,3,3,3,4,4,5,5,5,6,6,6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [16]:
a

array([42, 74, 63, 42, 99, 77, 95, 44,  1, 98, 23, 11, 38, 90, 45])

In [17]:
np.where(a>50) # return indices of all the values which are satisfied by the given condition

(array([ 1,  2,  4,  5,  6,  9, 13], dtype=int64),)

In [18]:
np.where(a>50, 0, a)

array([42,  0,  0, 42,  0,  0,  0, 44,  1,  0, 23, 11, 38,  0, 45])

In [19]:
np.cumsum(a)

array([ 42, 116, 179, 221, 320, 397, 492, 536, 537, 635, 658, 669, 707,
       797, 842])

In [20]:
b

array([[78, 86, 88, 97],
       [29, 72,  8, 71],
       [80, 14, 38, 65],
       [74, 97, 10, 41],
       [17, 44, 91, 40],
       [81, 15, 20, 71]])

In [22]:
np.cumsum(b, axis = 1)   # axis[col => 0, row => 1]

array([[ 78, 164, 252, 349],
       [ 29, 101, 109, 180],
       [ 80,  94, 132, 197],
       [ 74, 171, 181, 222],
       [ 17,  61, 152, 192],
       [ 81,  96, 116, 187]])